### ISSUE TITLE
ConnectionFinding.py error. Can't find KICAD environment variables

### ISSUE THREAD

**Issue by ObaidAshraf** [s39674/Image2schematic#12]
I am getting the below error when I try to execute ConnectionFinding.py with default conditions:

![image](https://user-images.githubusercontent.com/10379110/172926263-a70170c6-d9e7-4059-a5df-db426a4213f7.png)

Below are the logs:

> PS E:\Work\Image2schematic> & C:/Python310/python.exe e:/Work/Image2schematic/ConnectionFinding.py
WARNING: KICAD_SYMBOL_DIR environment variable is missing, so the default KiCad symbol libraries won't be searched. @ [E:\Work\Image2schematic\<frozen importlib._bootstrap_external>:883=>E:\Work\Image2schematic\<frozen importlib._bootstrap>:241]
looping over contours
Approx:  4
Area:  10143.0
found ic at: 114,37 to: 178,199
Chip name: MCU_Microchip_ATtiny
Pins:
right line x of Ic: 178
WARNING: Could not load KiCad schematic library "MCU_Microchip_ATtiny", falling back to backup library. @ [e:\Work\Image2schematic\ConnectionFinding.py:198]
Traceback (most recent call last):
  File "e:\Work\Image2schematic\ConnectionFinding.py", line 209, in <module>
    while f"/{i}/" not in CurrentICqueryResult[i]:
IndexError: list index out of range
PS E:\Work\Image2schematic> & C:/Python310/python.exe e:/Work/Image2schematic/ConnectionFinding.py
WARNING: KICAD_SYMBOL_DIR environment variable is missing, so the default KiCad symbol libraries won't be searched. @ [E:\Work\Image2schematic\<frozen importlib._bootstrap_external>:883=>E:\Work\Image2schematic\<frozen importlib._bootstrap>:241]
looping over contours
Approx:  4
Area:  10143.0
found ic at: 114,37 to: 178,199
Chip name: MCU_Microchip_ATtiny
Pins:
right line x of Ic: 178
WARNING: Could not load KiCad schematic library "MCU_Microchip_ATtiny", falling back to backup library. @ [e:\Work\Image2schematic\ConnectionFinding.py:198]
Traceback (most recent call last):
  File "e:\Work\Image2schematic\ConnectionFinding.py", line 209, in <module>
    while f"/{i}/" not in CurrentICqueryResult[i]:
IndexError: list index out of range

The error seems to be related with skidl package .. Is there any installation steps which I missed?

Thanks !!

**Comment by ObaidAshraf** [comment]
It turns out that KiCAD is required to be installed for skidl , as mentioned in below URL:
https://devbisme.github.io/skidl/#installation

I will go through the procedure and update README accordingly.
Thanks !

**Comment by s39674** [comment]
I apologize, this should have been in the installation guide, I will add that in the next commit.

**Comment by s39674** [comment]
@ObaidAshraf But if you don't need `KiCAD` you can just install the part libraries: https://gitlab.com/kicad/libraries/kicad-symbols and create an environment variable pointing to it: `setx KICAD_SYMBOL_DIR="/path/to/kicad/symbols/"`,
Thanks!

**Comment by ObaidAshraf** [comment]
@s39674 , that's a good alternative to get it up & working quickly without the hassle of downloading and installing KiCAD .. If it is tested to be working, then this issue can be Closed.

**Comment by s39674** [comment]
@ObaidAshraf it works fine for linux, not sure about windows.

**Comment by ObaidAshraf** [comment]
@s39674  I will have it checked and update

**Comment by ObaidAshraf** [comment]
The symbols from the below URL are working. Closing the issue.
https://gitlab.com/kicad/libraries/kicad-symbols
