### ISSUE TITLE
KiCAD chip database lacking info

### ISSUE THREAD

**Issue by s39674** [s39674/Image2schematic#15]
Right now, in `Dev - EasyOCR` branch, we send the chip detected text to skidl `search()` to query `KiCAD` chip pinout database (more info: https://devbisme.github.io/skidl/#finding-parts). But that database often doesn't support medium-to-large chips like micro processors. Does anyone know of a good database that does have support for those chips and python can interact with it? Thanks!

**Comment by s39674** [comment]
@ObaidAshraf For sure: TC1427, TUSB3410, TEA19051, RTL8101L, SiS900, IT8892E and more. Right now I'm working on a fallback solution, but I think we should have some sort of a user interaction so we could fill in the missing data, what do you think?

**Comment by ObaidAshraf** [comment]
@s39674 There are some websites like:
1) https://octopart.com/
2) https://www.findchips.com/

Octopart also provides APIs to fetch component but I think it is paid and has limits for free usage. 
There is one workaround, to avoid buying API, is we scrap the required information from these websites and use it in the code.
Tell me what do you think?
Also, can you mention what kind of information do you get from existing KiCAD symbols like Pin numbers, pin connections etc ??

Thanks ..

**Comment by s39674** [comment]
@ObaidAshraf thank you, that sounds good. I think the first option should be to query KiCAD library and if nothing is found then we could use the `requests` library to send an HTTP request and extract the necessary data. That sounds like a big project, I think it deserves a unique branch.

Right now we just get information about each pin, but in the future we can also get the schematic symbol of that chip and his dimensions.

**Comment by ObaidAshraf** [comment]
@s39674 Yes .. It should have a separate branch .. Additionally, the information about each pin usually in the datasheet (.pdf) file .. I am assuming that you are not talking about number of pins associated with the device..
Thanks !

**Comment by s39674** [comment]
I'm closing this issue for now as https://github.com/s39674/Image2schematic/pull/24 provides a temp fix for this. Thank you for your support!
